### ISSUE TITLE
Melodic release?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-release/opw_kinematics-release#1]
As came up in https://github.com/ros-planning/moveit/issues/2746, it would be nice to have a release of `opw_kinematics` targetting Melodic.

**Comment by Levi-Armstrong** [comment]
I have started the process.

**Comment by Levi-Armstrong** [comment]
Released.

**Comment by gavanderhoorn** [comment]
https://github.com/ros/rosdistro/pull/31368

**Comment by gavanderhoorn** [comment]
thanks
